#!/bin/bash

# By default, this server hook is disabled. If you want to enable it, uncomment the following lines.
:<<'COMMENT'
while read oldrev newrev refname
do
    if [[ $GL_USERNAME != "root" ]] && git diff-tree --no-commit-id --name-only -r $newrev | grep -q '.gitlab-ci.yml'; then
        echo "GL-HOOK-ERR: You cannot modify .gitlab-ci.yml. Please contact the root user."
        exit 1
    fi
done
COMMENT

exit 0