#!/bin/bash

while read oldrev newrev refname
do
    if [[ $GL_USERNAME != "root" ]] && git diff-tree --no-commit-id --name-only -r $newrev | grep -q '.gitlab-ci.yml'; then
        echo "GL-HOOK-ERR: You cannot modify .gitlab-ci.yml. Please contact the root user."
        exit 1
    fi
done

exit 0